package zug.enums;

public enum ActionEndReason {
	SUCCESS, INCOHERENT, INDEX_OUT_OF_RANGE, TOO_EXPENSIVE, MAX_TURN,
	MAX_GAME, OBSTRUCTED, NO_TARGET, NO_INITIATOR, NOT_PACMAN,
	TOO_FAR, CANT_DIE_TWICE, CANT_DIE_EXILED, UNBANDAGED_BOW,
	CANT_BANDAGE_TWICE, CANT_UNBANDAGE_TWICE, BOW_UNBANDAGED
}
