package zug;

public enum ActionEndReason {
	SUCCESS,INDEX_OUT_OF_RANGE,TOO_EXPENSIVE,MAX_TURN,
	MAX_GAME,OBSTRUCTED,NO_TARGET,NO_INITIATOR,NOT_PACMAN,
	TOO_FAR,CANT_DIE_TWICE,CANT_DIE_EXILED,UNBANDAGED_BOW,
	CANT_BANDAGE_TWICE,CANT_UNBANDAGE_UNBANDAGED,BOW_UNBANDAGED;
}
